### ISSUE TITLE
the reason "/(win|windows)11/g" not work

### ISSUE THREAD

**Issue by xyqlx** [AdhesionTek/Quantum-Wormhole#14]
https://github.com/AdhesionTek/Quantum-Wormhole/blob/3ab0ffdf0cf31a69178680180f2ac4c1ddcd51ce/index.js#L40

do not add quote when using regex:

```javascript
if (nameInput.value.toLowerCase().match(/(win|windows)11/g)) {
    canvasSrt="https://www.bilibili.com/video/BV1yb4y1x7Ky";
}
```

**Comment by WordlessEcho** [comment]
I made a pull request: #15

**Comment by AdhesionTek** [comment]
I was aware of that. But I am pretty sure it didn’t work. That was a temporary fix. I will merge your commitment.
