### ISSUE TITLE
You can build with Vercel

### ISSUE THREAD

**Issue by nyancatda** [AdhesionTek/Quantum-Wormhole#4]
これは中国大陸のユーザーにとってより友好的です。

https://vercel.com/

**Comment by frienkie** [comment]
> これは中国大陸のユーザーにとってより友好的です。
> 
> https://vercel.com/

本気ですか？
vercelのDNSは慢性的に不安定です。
無料のネットワークトラフィックも限界がある

**Comment by nyancatda** [comment]
本気です

**Comment by AdhesionTek** [comment]
Sorry, but based on my understanding, there is no inconvenience in using GitHub in China. 
Thus, we are not planning to move to another platform in the foreseeable future.
